name: ESP-IDF Build
​on:
push:
branches: [ "*" ]
​jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout Code
uses: actions/checkout@v3
​- name: Build with ESP-IDF
uses: espressif/esp-idf-ci-action@v1
with:
esp_idf_version: v4.4
target: esp32
path: '.'
​- name: Upload Firmware Artifacts
uses: actions/upload-artifact@v3
with:
name: TSDZ2-Firmware-BIN
path: 
build/bootloader/bootloader.bin
build/partition_table/partition-table.bin
build/*.bin